<section class="info-column" style="float:left;"><div class="info-title">Инфорамция</div>
<div class="info-cont">Год: <a href="/online/year/[xfvalue_year]" title="[xfvalue_year]">[xfvalue_year]</a><br>
Тип: <a href="/online/type/[xfvalue_type]" title="Тип: [xfvalue_type]">[xfvalue_type]</a><br>Эпизоды: [xfvalue_episode]<br>Выпуск: [xfvalue_year2]<br>
Жанр: [xfvalue_genre]<br>
Автор оригинала: <a href="/online/authoro/[xfvalue_authoro]" title="[xfvalue_authoro]">[xfvalue_authoro]</a><br>
Режиссер: <a href="/online/authoro/[xfvalue_director]" title="[xfvalue_director]">[xfvalue_director]</a><br>
Статус: <a href="/online/status/[xfvalue_status]" title="[xfvalue_status]">[xfvalue_status]</a><br><br>
[xfgiven_sub]Перевод: [xfvalue_sub]<br>[/xfgiven_sub]
[xfgiven_dub]Озвучивание: [xfvalue_dub]<br><br>[/xfgiven_dub]
Источник: <a target="_blank" href="http://[xfvalue_video-player].uz" tytle="[xfvalue_video-player].Uz" alt="[xfvalue_video-player].Uz">[xfvalue_video-player].Uz</a><br>
Видео залил: <a target="_blank" href="http://mover.uz/channel/[xfvalue_video-rel]/" tytle="http://mover.uz/channel/[xfvalue_video-rel]/" alt="http://mover.uz/channel/[xfvalue_video-rel]/">[xfvalue_video-rel]</a></div>
<div class="info-title">Студия: </div><div class="info-cont" style="text-align:center;padding:8px;"><a href="/online/studio/[xfvalue_studio]" title="[xfvalue_studio]">[xfvalue_studio]</a></div>
<!--<a href=''><button class="info-button download">Скачать торрент</button></a>--></section>
<section class="descr-column" style="float:left;"><div class="info-title">Описание</div><div class="info-cont">{full-story}</div>
<div class="info-title">Скриншоты</div><div class="info-cont">
<div class="clearfix"><div class="info-screen">
[xfgiven_scr-online-1]<a href="[xfvalue_scr-online-1]" rel="highslide" class="highslide"><img src="[xfvalue_scr-online-1]" alt='Скрин #1' title='Скрин #1'/></a><a href="[xfvalue_scr-online-2]" rel="highslide" class="highslide"><img src="[xfvalue_scr-online-2]" alt='Скрин #2' title='Скрин #2'/></a><a href="[xfvalue_scr-online-3]" rel="highslide" class="highslide"><img src="[xfvalue_scr-online-3]" alt='Скрин #3' title='Скрин #3'/></a>[/xfgiven_scr-online-1]</div></div></div></section>
<section class="poster-column"><img src="[xfvalue_poster]" class="info-poster" alt="" /></section>
<div class="list"></div><div class="vk_multifilm"><div class="info-title">Онлайн просмотр</div>
<script language="JavaScript">function getTrueLink(link) {return link;} var old_id = -1; function plAnime(id,tid) {if ( old_id > 0 ) {if ( old_id%2 != 0 ) {document.getElementById('bt_div_'+old_id).className = 'ep1'; } else { document.getElementById('bt_div_'+old_id).className = 'ep2'; } } document.getElementById('bt_div_'+id).className = 'pcurrent'; old_id = id * 1; var innerCode = ""; var vid = getTrueLink(document.getElementById('ep_url_'+id).innerHTML); if ( tid == 1 ) {innerCode = '<object id="player" width="683" height="403" type="application/x-shockwave-flash" name="player" data="http://mover.uz/pl/p.swf"><param name="bgcolor" value="#000000"></param><param name="allowFullScreen" value="true"></param><param name="allowScriptAccess" value="always"></param><param name="wmode" value="opaque"></param><param name="flashvars" value="st=http://mover.uz/player?vn='+vid+'"></param><object>';} document.getElementById('vidplayer').innerHTML = innerCode; };</script>
<ul id="serial_selector">
<li id="bt_div_1" id="ep1" class="ep1" onclick="plAnime(1,1)">[xfvalue_name-onl-1]</li><p id="ep_url_1" style="display:none;">[xfvalue_s-online-1]</p>
[xfgiven_s-online-2]<li id="bt_div_2" id="ep2" class="ep2" onclick="plAnime(2,1)">[xfvalue_name-onl-2]</li><p id="ep_url_2" style="display:none;">[xfvalue_s-online-2]</p>[/xfgiven_s-online-2]
[xfgiven_s-online-3]<li id="bt_div_3" id="ep3" class="ep1" onclick="plAnime(3,1)">[xfvalue_name-onl-3]</li><p id="ep_url_3" style="display:none;">[xfvalue_s-online-3]</p>[/xfgiven_s-online-3]
[xfgiven_s-online-4]<li id="bt_div_4" id="ep4" class="ep2" onclick="plAnime(4,1)">[xfvalue_name-onl-4]</li><p id="ep_url_4" style="display:none;">[xfvalue_s-online-4]</p>[/xfgiven_s-online-4]
[xfgiven_s-online-5]<li id="bt_div_5" id="ep5" class="ep1" onclick="plAnime(5,1)">[xfvalue_name-onl-5]</li><p id="ep_url_5" style="display:none;">[xfvalue_s-online-5]</p>[/xfgiven_s-online-5]
[xfgiven_s-online-6]<li id="bt_div_6" id="ep6" class="ep2" onclick="plAnime(6,1)">[xfvalue_name-onl-6]</li><p id="ep_url_6" style="display:none;">[xfvalue_s-online-6]</p>[/xfgiven_s-online-6]
[xfgiven_s-online-7]<li id="bt_div_7" id="ep7" class="ep1" onclick="plAnime(7,1)">[xfvalue_name-onl-7]</li><p id="ep_url_7" style="display:none;">[xfvalue_s-online-7]</p>[/xfgiven_s-online-7]
[xfgiven_s-online-8]<li id="bt_div_8" id="ep8" class="ep2" onclick="plAnime(8,1)">[xfvalue_name-onl-8]</li><p id="ep_url_8" style="display:none;">[xfvalue_s-online-8]</p>[/xfgiven_s-online-8]
[xfgiven_s-online-9]<li id="bt_div_9" id="ep9" class="ep1" onclick="plAnime(9,1)">[xfvalue_name-onl-9]</li><p id="ep_url_9" style="display:none;">[xfvalue_s-online-9]</p>[/xfgiven_s-online-9]
[xfgiven_s-online-10]<li id="bt_div_10" id="ep10" class="ep2" onclick="plAnime(10,1)">[xfvalue_name-onl-10]</li><p id="ep_url_10" style="display:none;">[xfvalue_s-online-10]</p>[/xfgiven_s-online-10]
[xfgiven_s-online-11]<li id="bt_div_11" id="ep11" class="ep1" onclick="plAnime(11,1)">[xfvalue_name-onl-11]</li><p id="ep_url_11" style="display:none;">[xfvalue_s-online-11]</p>[/xfgiven_s-online-11]
[xfgiven_s-online-12]<li id="bt_div_12" id="ep12" class="ep2" onclick="plAnime(12,1)">[xfvalue_name-onl-12]</li><p id="ep_url_12" style="display:none;">[xfvalue_s-online-12]</p>[/xfgiven_s-online-12]
[xfgiven_s-online-13]<li id="bt_div_13" id="ep13" class="ep1" onclick="plAnime(13,1)">[xfvalue_name-onl-13]</li><p id="ep_url_13" style="display:none;">[xfvalue_s-online-13]</p>[/xfgiven_s-online-13]
[xfgiven_s-online-14]<li id="bt_div_14" id="ep14" class="ep2" onclick="plAnime(14,1)">[xfvalue_name-onl-14]</li><p id="ep_url_14" style="display:none;">[xfvalue_s-online-14]</p>[/xfgiven_s-online-14]
[xfgiven_s-online-15]<li id="bt_div_15" id="ep15" class="ep1" onclick="plAnime(15,1)">[xfvalue_name-onl-15]</li><p id="ep_url_15" style="display:none;">[xfvalue_s-online-15]</p>[/xfgiven_s-online-15]
[xfgiven_s-online-16]<li id="bt_div_16" id="ep16" class="ep2" onclick="plAnime(16,1)">[xfvalue_name-onl-16]</li><p id="ep_url_16" style="display:none;">[xfvalue_s-online-16]</p>[/xfgiven_s-online-16]
[xfgiven_s-online-17]<li id="bt_div_17" id="ep17" class="ep1" onclick="plAnime(17,1)">[xfvalue_name-onl-17]</li><p id="ep_url_17" style="display:none;">[xfvalue_s-online-17]</p>[/xfgiven_s-online-17]
[xfgiven_s-online-18]<li id="bt_div_18" id="ep18" class="ep2" onclick="plAnime(18,1)">[xfvalue_name-onl-18]</li><p id="ep_url_18" style="display:none;">[xfvalue_s-online-18]</p>[/xfgiven_s-online-18]
[xfgiven_s-online-19]<li id="bt_div_19" id="ep19" class="ep1" onclick="plAnime(19,1)">[xfvalue_name-onl-19]</li><p id="ep_url_19" style="display:none;">[xfvalue_s-online-19]</p>[/xfgiven_s-online-19]
[xfgiven_s-online-20]<li id="bt_div_20" id="ep20" class="ep2" onclick="plAnime(20,1)">[xfvalue_name-onl-20]</li><p id="ep_url_20" style="display:none;">[xfvalue_s-online-20]</p>[/xfgiven_s-online-20]
[xfgiven_s-online-21]<li id="bt_div_21" id="ep21" class="ep1" onclick="plAnime(21,1)">[xfvalue_name-onl-21]</li><p id="ep_url_21" style="display:none;">[xfvalue_s-online-21]</p>[/xfgiven_s-online-21]
[xfgiven_s-online-22]<li id="bt_div_22" id="ep22" class="ep2" onclick="plAnime(22,1)">[xfvalue_name-onl-22]</li><p id="ep_url_22" style="display:none;">[xfvalue_s-online-22]</p>[/xfgiven_s-online-22]
[xfgiven_s-online-23]<li id="bt_div_23" id="ep23" class="ep1" onclick="plAnime(23,1)">[xfvalue_name-onl-23]</li><p id="ep_url_23" style="display:none;">[xfvalue_s-online-23]</p>[/xfgiven_s-online-23]
[xfgiven_s-online-24]<li id="bt_div_24" id="ep24" class="ep2" onclick="plAnime(24,1)">[xfvalue_name-onl-24]</li><p id="ep_url_24" style="display:none;">[xfvalue_s-online-24]</p>[/xfgiven_s-online-24]
[xfgiven_s-online-25]<li id="bt_div_25" id="ep25" class="ep1" onclick="plAnime(25,1)">[xfvalue_name-onl-25]</li><p id="ep_url_25" style="display:none;">[xfvalue_s-online-25]</p>[/xfgiven_s-online-25]
[xfgiven_s-online-26]<li id="bt_div_26" id="ep26" class="ep2" onclick="plAnime(26,1)">[xfvalue_name-onl-26]</li><p id="ep_url_26" style="display:none;">[xfvalue_s-online-26]</p>[/xfgiven_s-online-26]
[xfgiven_s-online-27]<li id="bt_div_27" id="ep27" class="ep1" onclick="plAnime(27,1)">[xfvalue_name-onl-27]</li><p id="ep_url_27" style="display:none;">[xfvalue_s-online-27]</p>[/xfgiven_s-online-27]
[xfgiven_s-online-28]<li id="bt_div_28" id="ep28" class="ep2" onclick="plAnime(28,1)">[xfvalue_name-onl-28]</li><p id="ep_url_28" style="display:none;">[xfvalue_s-online-28]</p>[/xfgiven_s-online-28]
[xfgiven_s-online-29]<li id="bt_div_29" id="ep29" class="ep1" onclick="plAnime(29,1)">[xfvalue_name-onl-29]</li><p id="ep_url_29" style="display:none;">[xfvalue_s-online-29]</p>[/xfgiven_s-online-29]
[xfgiven_s-online-30]<li id="bt_div_30" id="ep30" class="ep2" onclick="plAnime(30,1)">[xfvalue_name-onl-30]</li><p id="ep_url_30" style="display:none;">[xfvalue_s-online-30]</p>[/xfgiven_s-online-30]
[xfgiven_s-online-31]<li id="bt_div_31" id="ep31" class="ep1" onclick="plAnime(31,1)">[xfvalue_name-onl-31]</li><p id="ep_url_31" style="display:none;">[xfvalue_s-online-31]</p>[/xfgiven_s-online-31]
[xfgiven_s-online-32]<li id="bt_div_32" id="ep32" class="ep2" onclick="plAnime(32,1)">[xfvalue_name-onl-32]</li><p id="ep_url_32" style="display:none;">[xfvalue_s-online-32]</p>[/xfgiven_s-online-32]
[xfgiven_s-online-33]<li id="bt_div_33" id="ep33" class="ep1" onclick="plAnime(33,1)">[xfvalue_name-onl-33]</li><p id="ep_url_33" style="display:none;">[xfvalue_s-online-33]</p>[/xfgiven_s-online-33]
[xfgiven_s-online-34]<li id="bt_div_34" id="ep34" class="ep2" onclick="plAnime(34,1)">[xfvalue_name-onl-34]</li><p id="ep_url_34" style="display:none;">[xfvalue_s-online-34]</p>[/xfgiven_s-online-34]
[xfgiven_s-online-35]<li id="bt_div_35" id="ep35" class="ep1" onclick="plAnime(35,1)">[xfvalue_name-onl-35]</li><p id="ep_url_35" style="display:none;">[xfvalue_s-online-35]</p>[/xfgiven_s-online-35]
[xfgiven_s-online-36]<li id="bt_div_36" id="ep36" class="ep2" onclick="plAnime(36,1)">[xfvalue_name-onl-36]</li><p id="ep_url_36" style="display:none;">[xfvalue_s-online-36]</p>[/xfgiven_s-online-36]
[xfgiven_s-online-37]<li id="bt_div_37" id="ep37" class="ep1" onclick="plAnime(37,1)">[xfvalue_name-onl-37]</li><p id="ep_url_37" style="display:none;">[xfvalue_s-online-37]</p>[/xfgiven_s-online-37]
[xfgiven_s-online-38]<li id="bt_div_38" id="ep38" class="ep2" onclick="plAnime(38,1)">[xfvalue_name-onl-38]</li><p id="ep_url_38" style="display:none;">[xfvalue_s-online-38]</p>[/xfgiven_s-online-38]
[xfgiven_s-online-39]<li id="bt_div_39" id="ep39" class="ep1" onclick="plAnime(39,1)">[xfvalue_name-onl-39]</li><p id="ep_url_39" style="display:none;">[xfvalue_s-online-39]</p>[/xfgiven_s-online-39]
[xfgiven_s-online-40]<li id="bt_div_40" id="ep40" class="ep2" onclick="plAnime(40,1)">[xfvalue_name-onl-40]</li><p id="ep_url_40" style="display:none;">[xfvalue_s-online-40]</p>[/xfgiven_s-online-40]
[xfgiven_s-online-41]<li id="bt_div_41" id="ep41" class="ep1" onclick="plAnime(41,1)">[xfvalue_name-onl-41]</li><p id="ep_url_41" style="display:none;">[xfvalue_s-online-41]</p>[/xfgiven_s-online-41]
[xfgiven_s-online-42]<li id="bt_div_42" id="ep42" class="ep2" onclick="plAnime(42,1)">[xfvalue_name-onl-42]</li><p id="ep_url_42" style="display:none;">[xfvalue_s-online-42]</p>[/xfgiven_s-online-42]
[xfgiven_s-online-43]<li id="bt_div_43" id="ep43" class="ep1" onclick="plAnime(43,1)">[xfvalue_name-onl-43]</li><p id="ep_url_43" style="display:none;">[xfvalue_s-online-43]</p>[/xfgiven_s-online-43]
[xfgiven_s-online-44]<li id="bt_div_44" id="ep44" class="ep2" onclick="plAnime(44,1)">[xfvalue_name-onl-44]</li><p id="ep_url_44" style="display:none;">[xfvalue_s-online-44]</p>[/xfgiven_s-online-44]
[xfgiven_s-online-45]<li id="bt_div_45" id="ep45" class="ep1" onclick="plAnime(45,1)">[xfvalue_name-onl-45]</li><p id="ep_url_45" style="display:none;">[xfvalue_s-online-45]</p>[/xfgiven_s-online-45]
[xfgiven_s-online-46]<li id="bt_div_46" id="ep46" class="ep2" onclick="plAnime(46,1)">[xfvalue_name-onl-46]</li><p id="ep_url_46" style="display:none;">[xfvalue_s-online-46]</p>[/xfgiven_s-online-46]
[xfgiven_s-online-47]<li id="bt_div_47" id="ep47" class="ep1" onclick="plAnime(47,1)">[xfvalue_name-onl-47]</li><p id="ep_url_47" style="display:none;">[xfvalue_s-online-47]</p>[/xfgiven_s-online-47]
[xfgiven_s-online-48]<li id="bt_div_48" id="ep48" class="ep2" onclick="plAnime(48,1)">[xfvalue_name-onl-48]</li><p id="ep_url_48" style="display:none;">[xfvalue_s-online-48]</p>[/xfgiven_s-online-48]
[xfgiven_s-online-49]<li id="bt_div_49" id="ep49" class="ep1" onclick="plAnime(49,1)">[xfvalue_name-onl-49]</li><p id="ep_url_49" style="display:none;">[xfvalue_s-online-49]</p>[/xfgiven_s-online-49]
[xfgiven_s-online-50]<li id="bt_div_50" id="ep50" class="ep2" onclick="plAnime(50,1)">[xfvalue_name-onl-50]</li><p id="ep_url_50" style="display:none;">[xfvalue_s-online-50]</p>[/xfgiven_s-online-50]
[xfgiven_s-online-51]<li id="bt_div_51" id="ep51" class="ep1" onclick="plAnime(51,1)">[xfvalue_name-onl-51]</li><p id="ep_url_51" style="display:none;">[xfvalue_s-online-51]</p>[/xfgiven_s-online-51]
[xfgiven_s-online-52]<li id="bt_div_52" id="ep52" class="ep2" onclick="plAnime(52,1)">[xfvalue_name-onl-52]</li><p id="ep_url_52" style="display:none;">[xfvalue_s-online-52]</p>[/xfgiven_s-online-52]
[xfgiven_s-online-53]<li id="bt_div_53" id="ep53" class="ep1" onclick="plAnime(53,1)">[xfvalue_name-onl-53]</li><p id="ep_url_53" style="display:none;">[xfvalue_s-online-53]</p>[/xfgiven_s-online-53]
[xfgiven_s-online-54]<li id="bt_div_54" id="ep54" class="ep2" onclick="plAnime(54,1)">[xfvalue_name-onl-54]</li><p id="ep_url_54" style="display:none;">[xfvalue_s-online-54]</p>[/xfgiven_s-online-54]
[xfgiven_s-online-55]<li id="bt_div_55" id="ep55" class="ep1" onclick="plAnime(55,1)">[xfvalue_name-onl-55]</li><p id="ep_url_55" style="display:none;">[xfvalue_s-online-55]</p>[/xfgiven_s-online-55]
[xfgiven_s-online-56]<li id="bt_div_56" id="ep56" class="ep2" onclick="plAnime(56,1)">[xfvalue_name-onl-56]</li><p id="ep_url_56" style="display:none;">[xfvalue_s-online-56]</p>[/xfgiven_s-online-56]
[xfgiven_s-online-57]<li id="bt_div_57" id="ep57" class="ep1" onclick="plAnime(57,1)">[xfvalue_name-onl-57]</li><p id="ep_url_57" style="display:none;">[xfvalue_s-online-57]</p>[/xfgiven_s-online-57]
[xfgiven_s-online-58]<li id="bt_div_58" id="ep58" class="ep2" onclick="plAnime(58,1)">[xfvalue_name-onl-58]</li><p id="ep_url_58" style="display:none;">[xfvalue_s-online-58]</p>[/xfgiven_s-online-58]
[xfgiven_s-online-59]<li id="bt_div_59" id="ep59" class="ep1" onclick="plAnime(59,1)">[xfvalue_name-onl-59]</li><p id="ep_url_59" style="display:none;">[xfvalue_s-online-59]</p>[/xfgiven_s-online-59]
[xfgiven_s-online-60]<li id="bt_div_60" id="ep60" class="ep2" onclick="plAnime(60,1)">[xfvalue_name-onl-60]</li><p id="ep_url_60" style="display:none;">[xfvalue_s-online-60]</p>[/xfgiven_s-online-60]
[xfgiven_s-online-61]<li id="bt_div_61" id="ep61" class="ep1" onclick="plAnime(61,1)">[xfvalue_name-onl-61]</li><p id="ep_url_61" style="display:none;">[xfvalue_s-online-61]</p>[/xfgiven_s-online-61]
[xfgiven_s-online-62]<li id="bt_div_62" id="ep62" class="ep2" onclick="plAnime(62,1)">[xfvalue_name-onl-62]</li><p id="ep_url_62" style="display:none;">[xfvalue_s-online-62]</p>[/xfgiven_s-online-62]
[xfgiven_s-online-63]<li id="bt_div_63" id="ep63" class="ep1" onclick="plAnime(63,1)">[xfvalue_name-onl-63]</li><p id="ep_url_63" style="display:none;">[xfvalue_s-online-63]</p>[/xfgiven_s-online-63]
[xfgiven_s-online-64]<li id="bt_div_64" id="ep64" class="ep2" onclick="plAnime(64,1)">[xfvalue_name-onl-64]</li><p id="ep_url_64" style="display:none;">[xfvalue_s-online-64]</p>[/xfgiven_s-online-64]
[xfgiven_s-online-65]<li id="bt_div_65" id="ep65" class="ep1" onclick="plAnime(65,1)">[xfvalue_name-onl-65]</li><p id="ep_url_65" style="display:none;">[xfvalue_s-online-65]</p>[/xfgiven_s-online-65]
[xfgiven_s-online-66]<li id="bt_div_66" id="ep66" class="ep2" onclick="plAnime(66,1)">[xfvalue_name-onl-66]</li><p id="ep_url_66" style="display:none;">[xfvalue_s-online-66]</p>[/xfgiven_s-online-66]
[xfgiven_s-online-67]<li id="bt_div_67" id="ep67" class="ep1" onclick="plAnime(67,1)">[xfvalue_name-onl-67]</li><p id="ep_url_67" style="display:none;">[xfvalue_s-online-67]</p>[/xfgiven_s-online-67]
[xfgiven_s-online-68]<li id="bt_div_68" id="ep68" class="ep2" onclick="plAnime(68,1)">[xfvalue_name-onl-68]</li><p id="ep_url_68" style="display:none;">[xfvalue_s-online-68]</p>[/xfgiven_s-online-68]
[xfgiven_s-online-69]<li id="bt_div_69" id="ep69" class="ep1" onclick="plAnime(69,1)">[xfvalue_name-onl-69]</li><p id="ep_url_69" style="display:none;">[xfvalue_s-online-69]</p>[/xfgiven_s-online-69]
[xfgiven_s-online-70]<li id="bt_div_70" id="ep70" class="ep2" onclick="plAnime(70,1)">[xfvalue_name-onl-70]</li><p id="ep_url_70" style="display:none;">[xfvalue_s-online-70]</p>[/xfgiven_s-online-70]
[xfgiven_s-online-71]<li id="bt_div_71" id="ep71" class="ep1" onclick="plAnime(71,1)">[xfvalue_name-onl-71]</li><p id="ep_url_71" style="display:none;">[xfvalue_s-online-71]</p>[/xfgiven_s-online-71]
[xfgiven_s-online-72]<li id="bt_div_72" id="ep72" class="ep2" onclick="plAnime(72,1)">[xfvalue_name-onl-72]</li><p id="ep_url_72" style="display:none;">[xfvalue_s-online-72]</p>[/xfgiven_s-online-72]
[xfgiven_s-online-73]<li id="bt_div_73" id="ep73" class="ep1" onclick="plAnime(73,1)">[xfvalue_name-onl-73]</li><p id="ep_url_73" style="display:none;">[xfvalue_s-online-73]</p>[/xfgiven_s-online-73]
[xfgiven_s-online-74]<li id="bt_div_74" id="ep74" class="ep2" onclick="plAnime(74,1)">[xfvalue_name-onl-74]</li><p id="ep_url_74" style="display:none;">[xfvalue_s-online-74]</p>[/xfgiven_s-online-74]
[xfgiven_s-online-75]<li id="bt_div_75" id="ep75" class="ep1" onclick="plAnime(75,1)">[xfvalue_name-onl-75]</li><p id="ep_url_75" style="display:none;">[xfvalue_s-online-75]</p>[/xfgiven_s-online-75]
[xfgiven_s-online-76]<li id="bt_div_76" id="ep76" class="ep2" onclick="plAnime(76,1)">[xfvalue_name-onl-76]</li><p id="ep_url_76" style="display:none;">[xfvalue_s-online-76]</p>[/xfgiven_s-online-76]
[xfgiven_s-online-77]<li id="bt_div_77" id="ep77" class="ep1" onclick="plAnime(77,1)">[xfvalue_name-onl-77]</li><p id="ep_url_77" style="display:none;">[xfvalue_s-online-77]</p>[/xfgiven_s-online-77]
[xfgiven_s-online-78]<li id="bt_div_78" id="ep78" class="ep2" onclick="plAnime(78,1)">[xfvalue_name-onl-78]</li><p id="ep_url_78" style="display:none;">[xfvalue_s-online-78]</p>[/xfgiven_s-online-78]
[xfgiven_s-online-79]<li id="bt_div_79" id="ep79" class="ep1" onclick="plAnime(79,1)">[xfvalue_name-onl-79]</li><p id="ep_url_79" style="display:none;">[xfvalue_s-online-79]</p>[/xfgiven_s-online-79]
[xfgiven_s-online-80]<li id="bt_div_80" id="ep80" class="ep2" onclick="plAnime(80,1)">[xfvalue_name-onl-80]</li><p id="ep_url_80" style="display:none;">[xfvalue_s-online-80]</p>[/xfgiven_s-online-80]
[xfgiven_s-online-81]<li id="bt_div_81" id="ep81" class="ep1" onclick="plAnime(81,1)">[xfvalue_name-onl-81]</li><p id="ep_url_81" style="display:none;">[xfvalue_s-online-81]</p>[/xfgiven_s-online-81]
[xfgiven_s-online-82]<li id="bt_div_82" id="ep82" class="ep2" onclick="plAnime(82,1)">[xfvalue_name-onl-82]</li><p id="ep_url_82" style="display:none;">[xfvalue_s-online-82]</p>[/xfgiven_s-online-82]
[xfgiven_s-online-83]<li id="bt_div_83" id="ep83" class="ep1" onclick="plAnime(83,1)">[xfvalue_name-onl-83]</li><p id="ep_url_83" style="display:none;">[xfvalue_s-online-83]</p>[/xfgiven_s-online-83]
[xfgiven_s-online-84]<li id="bt_div_84" id="ep84" class="ep2" onclick="plAnime(84,1)">[xfvalue_name-onl-84]</li><p id="ep_url_84" style="display:none;">[xfvalue_s-online-84]</p>[/xfgiven_s-online-84]
[xfgiven_s-online-85]<li id="bt_div_85" id="ep85" class="ep1" onclick="plAnime(85,1)">[xfvalue_name-onl-85]</li><p id="ep_url_85" style="display:none;">[xfvalue_s-online-85]</p>[/xfgiven_s-online-85]
[xfgiven_s-online-86]<li id="bt_div_86" id="ep86" class="ep2" onclick="plAnime(86,1)">[xfvalue_name-onl-86]</li><p id="ep_url_86" style="display:none;">[xfvalue_s-online-86]</p>[/xfgiven_s-online-86]
[xfgiven_s-online-87]<li id="bt_div_87" id="ep87" class="ep1" onclick="plAnime(87,1)">[xfvalue_name-onl-87]</li><p id="ep_url_87" style="display:none;">[xfvalue_s-online-87]</p>[/xfgiven_s-online-87]
[xfgiven_s-online-88]<li id="bt_div_88" id="ep88" class="ep2" onclick="plAnime(88,1)">[xfvalue_name-onl-88]</li><p id="ep_url_88" style="display:none;">[xfvalue_s-online-88]</p>[/xfgiven_s-online-88]
[xfgiven_s-online-89]<li id="bt_div_89" id="ep89" class="ep1" onclick="plAnime(89,1)">[xfvalue_name-onl-89]</li><p id="ep_url_89" style="display:none;">[xfvalue_s-online-89]</p>[/xfgiven_s-online-89]
[xfgiven_s-online-90]<li id="bt_div_90" id="ep90" class="ep2" onclick="plAnime(90,1)">[xfvalue_name-onl-90]</li><p id="ep_url_90" style="display:none;">[xfvalue_s-online-90]</p>[/xfgiven_s-online-90]
[xfgiven_s-online-91]<li id="bt_div_91" id="ep91" class="ep1" onclick="plAnime(91,1)">[xfvalue_name-onl-91]</li><p id="ep_url_91" style="display:none;">[xfvalue_s-online-91]</p>[/xfgiven_s-online-91]
[xfgiven_s-online-92]<li id="bt_div_92" id="ep92" class="ep2" onclick="plAnime(92,1)">[xfvalue_name-onl-92]</li><p id="ep_url_92" style="display:none;">[xfvalue_s-online-92]</p>[/xfgiven_s-online-92]
[xfgiven_s-online-93]<li id="bt_div_93" id="ep93" class="ep1" onclick="plAnime(93,1)">[xfvalue_name-onl-93]</li><p id="ep_url_93" style="display:none;">[xfvalue_s-online-93]</p>[/xfgiven_s-online-93]
[xfgiven_s-online-94]<li id="bt_div_94" id="ep94" class="ep2" onclick="plAnime(94,1)">[xfvalue_name-onl-94]</li><p id="ep_url_94" style="display:none;">[xfvalue_s-online-94]</p>[/xfgiven_s-online-94]
[xfgiven_s-online-95]<li id="bt_div_95" id="ep95" class="ep1" onclick="plAnime(95,1)">[xfvalue_name-onl-95]</li><p id="ep_url_95" style="display:none;">[xfvalue_s-online-95]</p>[/xfgiven_s-online-95]
[xfgiven_s-online-96]<li id="bt_div_96" id="ep96" class="ep2" onclick="plAnime(96,1)">[xfvalue_name-onl-96]</li><p id="ep_url_96" style="display:none;">[xfvalue_s-online-96]</p>[/xfgiven_s-online-96]
[xfgiven_s-online-97]<li id="bt_div_97" id="ep97" class="ep1" onclick="plAnime(97,1)">[xfvalue_name-onl-97]</li><p id="ep_url_97" style="display:none;">[xfvalue_s-online-97]</p>[/xfgiven_s-online-97]
[xfgiven_s-online-98]<li id="bt_div_98" id="ep98" class="ep2" onclick="plAnime(98,1)">[xfvalue_name-onl-98]</li><p id="ep_url_98" style="display:none;">[xfvalue_s-online-98]</p>[/xfgiven_s-online-98]
[xfgiven_s-online-99]<li id="bt_div_99" id="ep99" class="ep1" onclick="plAnime(99,1)">[xfvalue_name-onl-99]</li><p id="ep_url_99" style="display:none;">[xfvalue_s-online-99]</p>[/xfgiven_s-online-99]
[xfgiven_s-online-100]<li id="bt_div_100" id="ep100" class="ep2" onclick="plAnime(100,1)">[xfvalue_name-onl-100]</li><p id="ep_url_100" style="display:none;">[xfvalue_s-online-100]</p>[/xfgiven_s-online-100]
</ul>
<div id='vidplayer'><object name="film_main" id="film_main" width="683" height="403" type="application/x-shockwave-flash" data="http://mover.uz/pl/p.swf"><param name="bgcolor" value="#000000"></param><param name="allowFullScreen" value="true"></param><param name="allowScriptAccess" value="always"></param><param name="wmode" value="opaque"></param><param name="flashvars" value="st=http://mover.uz/player?vn=[xfvalue_s-online-1]"></param></object></div></div>